FROM flwr/clientapp:${FLWR_VERSION:-1.17.0}

WORKDIR /app
COPY --chown=app:app pyproject.toml .
RUN sed -i 's/.*flwr\[simulation\].*//' pyproject.toml \
  && python -m pip install -U --no-cache-dir .

ENTRYPOINT ["flwr-clientapp"]
